---
  - hosts: tag_Name_ClusterMaster
    user: ubuntu
    gather_facts: no
    become: yes
    become_method: sudo
    tasks:
      - name: Master node
        shell: /opt/splunk/bin/splunk edit cluster-config -mode master -replication_factor 3 -search_factor 2 -cluster_label IndexerCluster -secret patel -auth $auth:$pass ; /opt/splunk/bin/splunk restart

  - hosts: tag_Name_Indexer_*
    user: ubuntu
    gather_facts: no
    become: yes
    become_method: sudo
    tasks:
      - set_fact:
          temp: "{{ hostvars[inventory_hostname]['groups']['tag_Name_ClusterMaster'] | to_json }}"
          #fetch the ip of ClusterMaster
 
      - name: Indexer node
        shell: /opt/splunk/bin/splunk edit cluster-config -mode slave -master_uri https://{{ temp }}:8089 -replication_port 9887 -secret patel -auth $auth:$pass ; /opt/splunk/bin/splunk restart

  - hosts: tag_Name_SearchHead
    user: ubuntu
    gather_facts: no
    become: yes
    become_method: sudo
    tasks:
      - set_fact:
          temp: "{{ hostvars[inventory_hostname]['groups']['tag_Name_ClusterMaster'] | to_json }}"
          #fetch the ip of ClusterMaster

      - name: SearchHead node
        shell: /opt/splunk/bin/splunk edit cluster-config -mode searchhead -master_uri https://{{ temp }}:8089 -replication_port 9887 -secret patel -auth $auth:$pass ; /opt/splunk/bin/splunk restart
